var html = document.getElementsByTagName("html")[0];
html.innerHTML = html.innerHTML.replace(/placeholder_home/g, "<link rel='favicon' href='favicon.png' />Home");
html.innerHTML = html.innerHTML.replace(/placeholder_devteam/g, "<link rel='apple-mobile-touch-icon' href='favicon2.png' />Developers");
html.innerHTML = html.innerHTML.replace(/placeholder_projects/g, "<link rel='shortcut icon' href='favicon2.png' />Projects");
html.innerHTML = html.innerHTML.replace(/placeholder_downloads/g, "<link rel='icon' href='favicon2.png' />Applications");
html.innerHTML = html.innerHTML.replace(/placeholder_lg/g, "Lazy Guy Jimmy");
html.innerHTML = html.innerHTML.replace(/placeholder_h4l/g, "Hacks4live");
html.innerHTML = html.innerHTML.replace(/placeholder_ipg/g, "iPhoneGuy1101");
html.innerHTML = html.innerHTML.replace(/urlbase/g, "");
html.innerHTML = html.innerHTML.replace(/emoji_happy/g, "<img class='emoji' src='/emojis/happy.png' width=32 height=24 />");
